### ISSUE TITLE
Crash on a multiplayer when using a Recall stone

### ISSUE THREAD

**Issue by AutomaticDragon** [Vanhal/Recall-Stones#11]
Hi

I'm having an issue on a multiplayer server where every time a recall stone is used the client crashes.

```
[00:02:34] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at com.vanhal.recallstones.ItemBase.checkTarget(ItemBase.java:266) ~[ItemBase.class:?]
	at com.vanhal.recallstones.ItemBase.moveLocation(ItemBase.java:157) ~[ItemBase.class:?]
	at com.vanhal.recallstones.ItemRecallStone.func_77659_a(ItemRecallStone.java:33) ~[ItemRecallStone.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[00:02:34] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 14/06/15 00:02
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.vanhal.recallstones.ItemBase.checkTarget(ItemBase.java:266)
	at com.vanhal.recallstones.ItemBase.moveLocation(ItemBase.java:157)
	at com.vanhal.recallstones.ItemRecallStone.func_77659_a(ItemRecallStone.java:33)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.vanhal.recallstones.ItemBase.checkTarget(ItemBase.java:266)
	at com.vanhal.recallstones.ItemBase.moveLocation(ItemBase.java:157)
	at com.vanhal.recallstones.ItemRecallStone.func_77659_a(ItemRecallStone.java:33)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)

```
Server side however no error is thrown, it just reports the client to have timed out.

On rejoining to the server I spawn at the location the stone recalls to.

Thanks for your help!

**Comment by Vanhal** [comment]
Right that's fixed now.
